### ISSUE TITLE
Hello，你好！

### ISSUE THREAD

**Issue by fifexu** [aquariusStudio/cicada#5]
很抱歉再次打扰你，我注意到你更新了对missav.com的支持，可是没有发布新的打包版本。
如果我下载了你的git代码，如何能运行它使用最新版本呢？
另外期待你新的0.2打包版本，希望它早日到来，辛苦了！谢谢
我看到你写了中文帮助，所以如果你能用中文交流就更好了！：）

Sorry to bother you again, I noticed that you updated support for missav.com, but did not release a new packaged version.
If I download your git code, how can I run it to use the latest version?
Also looking forward to your new 0.2 packaged version, I hope it will arrive soon, hard work! thanks
I see you wrote Chinese help, so it would be better if you can communicate in Chinese! :)

**Comment by aquariusStudio** [comment]
0.12版本已经基本完成了，只是最近在学习日语，没太多时间测试，估计在6月上中旬打包发布，同时看看是否有时间加入自动升级功能（因为很多网站在不停的改变加密方式）。
0.2版本改动很大，可能要等几个月了。
如果你想支持新的网站，并不一定需要升级版本，往往只需要把
org.aquarius.cicada.core/resources/config/下面更新的文件复制到
Cicada运行目录/workspace/config即可。
针对Missav的支持，你直接找到相应目录复制过去即可。

fifexu ***@***.***> 于2022年5月26日周四 01:47写道：

**Comment by fifexu** [comment]
非常感谢你的方法 工作辛苦了！
我在使用的过程中使用的主要是0.1打包版本
不知道是因为网络还是代理的问题 我只能正常导出jable.tv的视频列表（暂时已经足够了）
其他的网站不是只能导出1000~2000个，就是报错无法导出列表，而已经导出的列表选择下载也经常失去响应或下载失败。
在使用的过程中，唯一能使用的jable.tv，我设定了同时只能下载1个任务 2个线程（如果超过这个数量就会循环错误超过20次导致失败）
及时是这样的设置情况下，也莫名经常出现同时开始了2个任务，过一会就会失败卡死了，凡是这样卡死的任务，我关闭软件之后再点击开始，就会失去响应，必须要删除重新下载。
另外下面针对网址的最大线程设置 也不太好用，没有遇到自动增加的情况（虽然明明有上述超过线程失败的情况），如果我去查连接网址手动输入前置网页，也不太好用，因为一个网站经常链接一些其他不固定的网页下载视频，导致限制任务数失效。从而失败卡死。
我们不着急你修改，只是帮你反馈这些问题，帮助它变得更好，请轻松自在的慢慢修复和改善它吧，谢谢

**Comment by fifexu** [comment]
为了避免这个循环20次失败就屏蔽任务，我只能设定很低的一个任务两个线程，这样下载就会变得很慢。所以也可以考虑将这个错误允许的上限增加，目前的最大值就是20，稍微超速就失败了。。

**Comment by aquariusStudio** [comment]
1.因为通过SWT调用IE，线程切换确实会引发问题，但我测试下，就是尽量只做一件事，比如你找个时间，专门把所有信息下载下来以后，后续每日更新，基本上就不会死了。
2.Jable.tv比较特殊，它是hls格式，表面是开了两个任务，但背后其实是多个线程在并发下载，我回头再测试一下，看看是否为其加入新的限制。
3.其它问题，我测试后看情况，但可能不会大改，因为后续0.2版本会换成Chrome或者Firefox，就做完全避免死锁类问题（但内存占用会非常可怕，Chrome的问题）。

**Comment by fifexu** [comment]
好的 我尝试一下 再次感谢

**Comment by aquariusStudio** [comment]
这个暂时没法解决，因为热度排序是每个网站自己定义的算法，可能是根据观看次数+发布时间+分数等因素动态计算的，可能每天/每小时/每分都在变化，这些计算因子都是后台数据，没有办法实时访问，所以没有办法跟踪。
你可以在浏览器里访问，找一个贴粘板工具，把所有的URL地址复制下来，然后在Cicada的解析视频里批量下载即可。

fifexu ***@***.***> 于2022年6月15日周三 00:50写道：

**Comment by lengshu** [comment]
> 

你好,可以打包分享一下吗?

**Comment by aquariusStudio** [comment]
> > 
> 
> 你好,可以打包分享一下吗?

已经可以直接下载完整的打包版本了。
