### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by biozzl** [aquariusStudio/cicada#6]
下载了Java runtime安装之后还是不能正常运行
是要安装什么依赖么？操作系统是Win10 X64

下面的错误的log
!SESSION 2022-07-15 22:24:46.440 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_333
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=zh_CN
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.aquarius.cicada.workbench 4 0 2022-07-15 22:24:54.662
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.aquarius.cicada.workbench [20]
  Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
    -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.12.100.v20210122-1731"; singleton:="true"
       org.eclipse.e4.ui.workbench [56]
         Unresolved requirement: Require-Bundle: org.eclipse.e4.core.commands; bundle-version="0.11.100"
           -> Bundle-SymbolicName: org.eclipse.e4.core.commands; bundle-version="0.13.0.v20201119-1132"; singleton:="true"
              org.eclipse.e4.core.commands [39]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
           -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.5.0.v20210115-1333"; singleton:="true"
              org.eclipse.e4.ui.services [54]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
  Unresolved requirement: Require-Bundle: org.eclipse.ui
    -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
       org.eclipse.ui [81]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.120.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.122.100.v20210215-1525"; singleton:="true"
              org.eclipse.ui.workbench [86]
                Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
                  -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.e4.ui.progress,  org.eclipse.e4.core.commands.tests"
                Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
                  -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench"
  Unresolved requirement: Require-Bundle: org.eclipse.ui.views
    -> Bundle-SymbolicName: org.eclipse.ui.views; bundle-version="3.11.0.v20210111-1351"; singleton:="true"
       org.eclipse.ui.views [84]
         Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.5.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.aquarius.downloader.ui
    -> Bundle-SymbolicName: org.aquarius.downloader.ui; bundle-version="0.1.0"; singleton:="true"
       org.aquarius.downloader.ui [23]
         Unresolved requirement: Require-Bundle: org.eclipse.ui
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.ui.intro
    -> Bundle-SymbolicName: org.eclipse.ui.intro; bundle-version="3.6.100.v20210119-2223"; singleton:="true"
       org.eclipse.ui.intro [83]
         Unresolved requirement: Require-Bundle: org.eclipse.help.base; bundle-version="[4.0.0,5.0.0)"; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.ui.views.log
    -> Bundle-SymbolicName: org.eclipse.ui.views.log; bundle-version="1.2.1400.v20210122-1423"; singleton:="true"
       org.eclipse.ui.views.log [85]
         Unresolved requirement: Require-Bundle: org.eclipse.core.filesystem; bundle-version="[1.1.0,2.0.0)"; resolution:="optional"
         Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.3.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.aquarius.ui
    -> Bundle-SymbolicName: org.aquarius.ui; bundle-version="0.1.0"; singleton:="true"
       org.aquarius.ui [28]
         Unresolved requirement: Require-Bundle: org.eclipse.ui
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY org.aquarius.cicada.workbench.extension 4 0 2022-07-15 22:24:54.662
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.aquarius.cicada.workbench.extension [21]
  Unresolved requirement: Require-Bundle: org.aquarius.ui
    -> Bundle-SymbolicName: org.aquarius.ui; bundle-version="0.1.0"; singleton:="true"
       org.aquarius.ui [28]
         Unresolved requirement: Require-Bundle: org.eclipse.ui
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
              org.eclipse.ui [81]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
                Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.120.0,4.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.122.100.v20210215-1525"; singleton:="true"
                     org.eclipse.ui.workbench [86]
                       Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
                         -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.e4.ui.progress,  org.eclipse.e4.core.commands.tests"
                            org.eclipse.e4.core.commands [39]
                              Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
                       Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
                         -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench"
  Unresolved requirement: Require-Bundle: org.aquarius.cicada.workbench
    -> Bundle-SymbolicName: org.aquarius.cicada.workbench; bundle-version="0.1.0"; singleton:="true"
       org.aquarius.cicada.workbench [20]
         Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
           -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.12.100.v20210122-1731"; singleton:="true"
              org.eclipse.e4.ui.workbench [56]
                Unresolved requirement: Require-Bundle: org.eclipse.e4.core.commands; bundle-version="0.11.100"
                  -> Bundle-SymbolicName: org.eclipse.e4.core.commands; bundle-version="0.13.0.v20201119-1132"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
                  -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.5.0.v20210115-1333"; singleton:="true"
                     org.eclipse.e4.ui.services [54]
                       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"
         Unresolved requirement: Require-Bundle: org.eclipse.ui
           -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.ui.views
           -> Bundle-SymbolicName: org.eclipse.ui.views; bundle-version="3.11.0.v20210111-1351"; singleton:="true"
              org.eclipse.ui.views [84]
                Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.5.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.aquarius.downloader.ui
           -> Bundle-SymbolicName: org.aquarius.downloader.ui; bundle-version="0.1.0"; singleton:="true"
              org.aquarius.downloader.ui [23]
                Unresolved requirement: Require-Bundle: org.eclipse.ui
                  -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.ui.intro
           -> Bundle-SymbolicName: org.eclipse.ui.intro; bundle-version="3.6.100.v20210119-2223"; singleton:="true"
              org.eclipse.ui.intro [83]
                Unresolved requirement: Require-Bundle: org.eclipse.help.base; bundle-version="[4.0.0,5.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.ui.views.log
           -> Bundle-SymbolicName: org.eclipse.ui.views.log; bundle-version="1.2.1400.v20210122-1423"; singleton:="true"
              org.eclipse.ui.views.log [85]
                Unresolved requirement: Require-Bundle: org.eclipse.core.filesystem; bundle-version="[1.1.0,2.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.3.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.119.0.v20210111-1350"; singleton:="true"

**Comment by biozzl** [comment]
[1657948359785.log](https://github.com/aquariusStudio/cicada/files/9125202/1657948359785.log)

**Comment by aquariusStudio** [comment]
从上面的日志看，你使用的是JRE1.8版本，而下载的包则是Eclipse4.17基础库，而后者需要JRE11才能运行。
所以你可以，直接下载打包好，且带有JRE的运行包就可以直接运行了，无须安装JRE（建议该方式），又或者把JRE1.8删除，安装JRE11。

**Comment by biozzl** [comment]
> 从上面的日志看，你使用的是JRE1.8版本，而下载的包则是Eclipse4.17基础库，而后者需要JRE11才能运行。 所以你可以，直接下载打包好，且带有JRE的运行包就可以直接运行了，无须安装JRE（建议该方式），又或者把JRE1.8删除，安装JRE11。

谢谢大佬，我下载的是0.12版本貌似没有打包JRE的运行包，能麻烦发布一个0.12版本的打包好的版本么？
或者是否告知JRE11在哪里可以下载，我找了一圈JAVA的主页没找到（新手对这个不太熟）
谢谢你！

**Comment by aquariusStudio** [comment]
已经打包上传了，是我的疏忽。
