### ISSUE TITLE
可是适配下 Njav.tv吗.

### ISSUE THREAD

**Issue by lengshu** [aquariusStudio/cicada#9]
感觉网页模式类似missav.但是自己复制过来修改的不管用
抱歉抱歉 .手快打错了.是Njav.tv

**Comment by aquariusStudio** [comment]
najv.tv 这个网站访问不了啊，好像是个钓鱼网站

**Comment by lengshu** [comment]
> [najv.tv](https://najv.tv) 这个网站访问不了啊，好像是个钓鱼网站

抱歉抱歉...手快打错了.是Njav.tv

**Comment by lengshu** [comment]
function internalParseMovieList() {
	var result = new Object();
	var movies = [];
	result.movieList = movies;

	var elementList = document.querySelectorAll("div.box-item");

	if (null != elementList) {
		for (var i = 0; i < elementList.length; i++) {
			var element = elementList[i];
			var movie = new Object();

			var titleElement = element.querySelector("div.detail");

			movie.title = titleElement.textContent;
			movie.title = titleElement.textContent;
			movie.title = movie.title.replace("\n\n", "");
			movie.title = movie.title.replace("\n\n", "");
			movie.title = movie.title.replace("\n\n", "");
			movie.title = movie.title.replace("\n", "");
			movie.title = movie.title.replace("\n", "");
			movie.title = movie.title.replace("\n", "");

			var linkElement = titleElement.querySelector("a");
			movie.pageUrl = linkElement.href;

			var imageElement = element.querySelector("img");
			movie.imageUrl = imageElement.src;

			if (movie.imageUrl.indexOf("data") == 0) {
			movie.imageUrl = imageElement.getAttribute("data-src");
			}

			movies.push(movie);
		}
	}

	var pageFormElement = document.querySelector("span#price-currency");
	if (null != pageFormElement) {
		var formString = pageFormElement.textContent;
		var stringIndex = formString.indexOf(" ");
		formString = formString.substr(stringIndex);
		result.totalPageCount = parseInt(formString);
	}

	var lastElement = document.querySelector("a[aria-label='pagination.next']");

	if (lastElement == null) {
		result.lastPage = true;
	}

	return result;
}

function doParseMovieList() {
	return JSON.stringify(internalParseMovieList());
}

return doParseMovieList();

自己尝试适配了一下.
config.json
{
	"checkDuplicationCount":1,
	"enable":true,
	"mainPage":"https://njav.tv",
	"movieChannelList":[
		{
			"autoRefreshDetail":true,
			"autoRefreshList":true,
			"name":"uncensored",
			"nlsDisplayName":"uncensored,zh_CN:uncensored,zh_TW:uncensored,ja:uncensored",
			"supportPaging":true,
			"urlPattern":"https://njav.tv/zh/uncensored?page={0}"
		},
		{
			"autoRefreshDetail":true,
			"autoRefreshList":true,
			"name":"leaked",
			"nlsDisplayName":"leaked,zh_CN:leaked,zh_TW:leaked,ja:leaked",
			"supportPaging":true,
			"urlPattern":"https://njav.tv/zh/uncensored-leaked?page={0}"
		}
				{
			"autoRefreshDetail":true,
			"autoRefreshList":true,
			"name":"fc2",
			"nlsDisplayName":"fc2,zh_CN:fc2,zh_TW:fc2,ja:fc2",
			"supportPaging":true,
			"urlPattern":"https://njav.tv/zh/tags/fc2?page={0}"
		}
						{
			"autoRefreshDetail":true,
			"autoRefreshList":true,
			"name":"decensored",
			"nlsDisplayName":"decensored,zh_CN:decensored,zh_TW:decensored,ja:decensored",
			"supportPaging":true,
			"urlPattern":"https://njav.tv/zh/decensored?page={0}"
		}
	],
	"parseMovieIdRegex":"",
	"siteName":"njav.tv",
	"supportAlbum":false,
	"supportImport":true,
	"supportJumpToLast":true,
	"supportMultiDownloadSource":false,
	"supportPaging":true,
	"validPeriod":180,
	"waitTime":5
}


但是 刷新不起作用,.是不是还需要改别的地方?

**Comment by lengshu** [comment]
自己修改了一份njav的..,不会入库 .上传到这里了
用原作者的missav的list.js,适配了njav
用原作者的missav的detail.js,适配了njav

[njav.tvvvvv.gz](https://github.com/aquariusStudio/cicada/files/10774695/njav.tvvvvv.gz)

**Comment by aquariusStudio** [comment]
> 自己修改了一份njav的..,不会入库 .上传到这里了 用原作者的missav的list.js,适配了njav 用原作者的missav的detail.js,适配了njav
> 
> [njav.tvvvvv.gz](https://github.com/aquariusStudio/cicada/files/10774695/njav.tvvvvv.gz)

我测试一下，如果OK，会入库，然后和missav的更新放入增量升级包中。
